auth_magic: yXRJGFBk9RqEtko724TR8tpiixf5Kzfj
password_hash_algos: sha256
shop_name: Amazone
force_ssl: null
admin_allow_host: {  }
cookie_lifetime: 0
cookie_name: eccube
locale: ja
timezone: Asia/Tokyo
pageinrange: false
trusted_proxies_connection_only: false
trusted_proxies: {  }
eccube_install: 1
